### DISCUSSION TITLE
How to use the --cli option with webui.py?

### DISCUSSION THREAD

**Discussion by viconx98** [hlky/stable-diffusion-webui#980] [Q&A]
I want to run a headless version on Google Colab, I tried looking around but couldn't find anything about the --cli argument except this small help string

> don't launch web server, take Python function kwargs from this file.

From what I understood, I need to pass a .yaml file path here but I have no idea what to actually put in this file to make it work.

Any help or detailed examples would be appreciated, Thanks!

**Comment by codedealer** [comment]
Check out #666 
I gave a simple example of what the file should look like. We do need a proper documentation for that but for now it should suffice.

**Reply by viconx98** [reply]
> Check out #666 I gave a simple example of what the file should look like. We do need a proper documentation for that but for now it should suffice.

Hi, thanks for the quick reply, I tried running it with this command on Colab
```
!python scripts/webui.py \
  --ckpt '{models_path}/sd-v1-4.ckpt' \
  --outdir '{output_path}' \
  --skip-grid \
  --cli "/content/drive/MyDrive/SD/stable-diffusion/configs/webui/cli.yaml"
```
But it just exits abruptly, Note that the ^C is not a manual keyboard interrupt from me, it just exits with that
![Command](https://i.imgur.com/KnuAR5B.png)

Heres what the cli.yaml looks like
```yaml
target: txt2img
prompt: ['cat in red hat']
ddim_steps: 50
sampler_name: k_lms

# Adding an int to toggles enables the corresponding feature.
# 0: Create prompt matrix (separate multiple prompts using |, and get all combinations of them)
# 1: Normalize Prompt Weights (ensure sum of weights add up to 1.0)
# 2: Save individual images
# 3: Save grid
# 4: Sort samples by prompt
# 5: Write sample info files
# 6: jpg samples
7: Fix faces using GFPGAN
8: Upscale images using Real-ESRGAN

toggles: [1, 2]
sampler_name: k_lms
ddim_eta: 0.0  # legacy name, applies to all algorithms.
n_iter: 1
batch_size: 4
cfg_scale: 7.5

# Leave blank for random seed:
seed:
height: 512
width: 512
fp:
realesrgan_model_name: 'RealESRGAN_x4plus'
variant_amount: 1.0
```
I am using a slightly modified version of [Altryne's Colab](https://colab.research.google.com/github/altryne/sd-webui-colab/blob/main/Stable_Diffusion_WebUi_Altryne.ipynb) that saves the files to my Google Drive so I don't have to download them again and again.

I am not very well versed in python but I tried adding some print statements in webui.py's main block, but apparently they're never executed so I assume the error happens somewhere else.

```python
if __name__ == '__main__':
    if opt.cli is None:
        print("Running Server")
        launch_server()
    else:
        print("Running Headless")
        run_headless()
```
Any help is appreciated, thanks!
